### ISSUE TITLE
System.out.println问题汇总分析

### ISSUE THREAD

**Issue by DingliZhang** [openjdk-riscv/jdk11u#307]
#### 测试用例：
```java
public class Foo {
    public static void main(String[] args) {
        long c = 100000000000L;
        System.out.println(c);
    }
}
```
使用bootjdk进行编译，rv32g-dev的jdk运行java命令
#### 输出结果：

![image](https://user-images.githubusercontent.com/19571377/148355872-cafcb796-c571-40c2-a71f-a2f803a42a9c.png)

#### 测试用例：
```java
public class Foo {
    public static void main(String[] args) {
        long c = 100000000000L;
        long d = 10000000000L;
        System.out.println(c/d);
    }
}
```
使用bootjdk进行编译，rv32g-dev的jdk运行java命令
#### 输出结果：
![image](https://user-images.githubusercontent.com/19571377/148356250-f28afc30-33ef-4025-bb76-aedd6b31833f.png)

#### 测试用例：
```diff
diff --git a/src/java.base/share/classes/java/util/JumboEnumSet.java b/src/java.base/share/classes/java/util/JumboEnumSet.java
index 20e8222ccc..69c51a2efa 100644
--- a/src/java.base/share/classes/java/util/JumboEnumSet.java
+++ b/src/java.base/share/classes/java/util/JumboEnumSet.java
@@ -136,6 +136,10 @@ class JumboEnumSet<E extends Enum<E>> extends EnumSet<E> {
             lastReturned = unseen & -unseen;
             lastReturnedIndex = unseenIndex;
             unseen -= lastReturned;
+            System.out.println("unseen= "+unseen);
+            System.out.println("unseenIndex= "+unseenIndex);
+            System.out.println("lastReturned= "+lastReturned);
+            System.out.println("lastReturnedIndex= "+lastReturnedIndex);
             return (E) universe[(lastReturnedIndex << 6)
                                 + Long.numberOfTrailingZeros(lastReturned)];
         }
```

打上patch后直接运行 `javac -version`

#### 部分输出结果：
```
unseen= .
unseenIndex= 0
lastReturned= 1
lastReturnedIndex= 0
unseen= ,
unseenIndex= 0
lastReturned= 2
lastReturnedIndex= 0
unseen= (
unseenIndex= 0
lastReturned= 4
lastReturnedIndex= 0
unseen= *
unseenIndex= 0
lastReturned= 8
lastReturnedIndex= 0
unseen= .
unseenIndex= 0
lastReturned=16
lastReturnedIndex= 0
unseen= ,
unseenIndex= 0
lastReturned=32
lastReturnedIndex= 0
unseen= (
unseenIndex= 0
lastReturned=64
lastReturnedIndex= 0
unseen= *
unseenIndex= 0
lastReturned128
lastReturnedIndex= 0
unseen= .
unseenIndex= 0
lastReturned256
lastReturnedIndex= 0
unseen= ,
unseenIndex= 0
lastReturned512
lastReturnedIndex= 0
unseen= (
unseenIndex= 0
lastReturne1024
lastReturnedIndex= 0
unseen= *
unseenIndex= 0
lastReturne2048
lastReturnedIndex= 0
unseen= .
unseenIndex= 0
lastReturne4096
lastReturnedIndex= 0
unseen= ,
unseenIndex= 0
lastReturne8192
lastReturnedIndex= 0
unseen= (
unseenIndex= 0
lastReturn16384
lastReturnedIndex= 0
unseen= *
unseenIndex= 0
lastReturn32768
lastReturnedIndex= 0
unseen= .
unseenIndex= 0
lastReturn65536
lastReturnedIndex= 0
unseen= ,
unseenIndex= 0
lastRetur131072
lastReturnedIndex= 0
unseen= (
unseenIndex= 0
lastRetur262144
lastReturnedIndex= 0
unseen= *
unseenIndex= 0
lastRetur524288
lastReturnedIndex= 0
unseen= .
unseenIndex= 0
lastRetu1048576
lastReturnedIndex= 0
unseen= ,
unseenIndex= 0
lastRetu2097152
lastReturnedIndex= 0
unseen= (
unseenIndex= 0
lastRetu4194304
lastReturnedIndex= 0
unseen= *
unseenIndex= 0
lastRetu8388608
lastReturnedIndex= 0
unseen= .
unseenIndex= 0
lastRet16777216
lastReturnedIndex= 0
unseen= ,
unseenIndex= 0
lastRet33554432
lastReturnedIndex= 0
unseen= (
unseenIndex= 0
lastRet67108864
lastReturnedIndex= 0
unseen= *
unseenIndex= 0
lastRe134217728
lastReturnedIndex= 0
unseen= .
unseenIndex= 0
lastRe268435456
lastReturnedIndex= 0
unseen= ,
unseenIndex= 0
lastRe536870912
lastReturnedIndex= 0
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -7 out of bounds for length 16
        at java.base/java.lang.Long.getChars(Long.java:555)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:802)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:254)
        at java.base/java.util.JumboEnumSet$EnumSetIterator.next(JumboEnumSet.java:139)
        at java.base/java.util.JumboEnumSet$EnumSetIterator.next(JumboEnumSet.java:97)
        at jdk.compiler/com.sun.tools.javac.main.Option.lookup(Option.java:917)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:374)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:193)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:229)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```
可以看到 `unseen` 的结果一直是有问题的，而 `lastReturned` 的结果往前缩进占用的字符的位置。

**Comment by zifeihan** [comment]
![image](https://user-images.githubusercontent.com/16839929/148398778-5daadffd-3932-4381-bca5-854cdd0723ac.png)
排查到 `void MacroAssembler::cmp_l2i(Register dst, Register src1, Register src2, Register tmp)` 函数应该存在逻辑没有覆盖全的情况，将该函数替换如下，即可实现 Long 类型数据正常打印。
```
void MacroAssembler::cmp_l2i(Register dst, Register src1, Register src2, Register tmp)
{
  if (src1 == src2) {
    mv(dst, zr);
    return;
  }
  Label done, done_lo;
  Register left_lo  = src1;
  Register left_hi  = src1 + 1;
  Register right_lo = src2;
  Register right_hi = src2 + 1;

  // compare high 32-bit
  // installs 1 if gt else 0
  slt(dst, right_hi, left_hi);
  bnez(dst, done);
  slt(dst, left_hi, right_hi);
  // dst = -1 if lt; else if eq , jump to compare low 32-bit
  neg(dst, dst);
  bnez(dst, done);
  sltz(tmp, right_hi);

  // compare low 32-bit
  // installs 1 if gt else 0
  sltu(dst, right_lo, left_lo);
  bnez(dst, done);
  sltu(dst, left_lo, right_lo);
  // dst = -1 if lt; else if eq , dst = 0
  neg(dst, dst);
  // bind(done_lo);
  // beqz(tmp, done);
  // neg(dst, dst);
  bind(done);
}
```

**Comment by DingliZhang** [comment]
修复后 https://github.com/openjdk-riscv/jdk11u/issues/307#issue-1095107310 中的 `直接输出Long类型数据` ，`输出Long型算式` 两种情况已经正确：
![image](https://user-images.githubusercontent.com/19571377/148485219-ce945a44-6f1e-447d-a328-0bf6fdd43515.png)

在JumboEnumSet.java中打印变量输出也已正确：
```
dingli@k9-plct:~/jdk11u$ /home/dingli/qemu-5.2.0-rv32/bin/qemu-riscv32 -L /opt/riscv32/sysroot /home/dingli/jdk11u/build/linux-riscv32-normal-core-slowdebug/jdk/bin/javac -version
unseen= 4294967294
unseenIndex= 0
lastReturned= 1
lastReturnedIndex= 0
unseen= 4294967292
unseenIndex= 0
lastReturned= 2
lastReturnedIndex= 0
unseen= 4294967288
unseenIndex= 0
lastReturned= 4
lastReturnedIndex= 0
unseen= 4294967280
unseenIndex= 0
lastReturned= 8
lastReturnedIndex= 0
unseen= 4294967264
unseenIndex= 0
lastReturned= 16
lastReturnedIndex= 0
unseen= 4294967232
unseenIndex= 0
lastReturned= 32
lastReturnedIndex= 0
unseen= 4294967168
unseenIndex= 0
lastReturned= 64
lastReturnedIndex= 0
unseen= 4294967040
unseenIndex= 0
lastReturned= 128
lastReturnedIndex= 0
unseen= 4294966784
unseenIndex= 0
lastReturned= 256
lastReturnedIndex= 0
unseen= 4294966272
unseenIndex= 0
lastReturned= 512
lastReturnedIndex= 0
unseen= 4294965248
unseenIndex= 0
lastReturned= 1024
lastReturnedIndex= 0
unseen= 4294963200
unseenIndex= 0
lastReturned= 2048
lastReturnedIndex= 0
unseen= 4294959104
unseenIndex= 0
lastReturned= 4096
lastReturnedIndex= 0
unseen= 4294950912
unseenIndex= 0
lastReturned= 8192
lastReturnedIndex= 0
unseen= 4294934528
unseenIndex= 0
lastReturned= 16384
lastReturnedIndex= 0
unseen= 4294901760
unseenIndex= 0
lastReturned= 32768
lastReturnedIndex= 0
unseen= 4294836224
unseenIndex= 0
lastReturned= 65536
lastReturnedIndex= 0
unseen= 4294705152
unseenIndex= 0
lastReturned= 131072
lastReturnedIndex= 0
unseen= 4294443008
unseenIndex= 0
lastReturned= 262144
lastReturnedIndex= 0
unseen= 4293918720
unseenIndex= 0
lastReturned= 524288
lastReturnedIndex= 0
unseen= 4292870144
unseenIndex= 0
lastReturned= 1048576
lastReturnedIndex= 0
unseen= 4290772992
unseenIndex= 0
lastReturned= 2097152
lastReturnedIndex= 0
unseen= 4286578688
unseenIndex= 0
lastReturned= 4194304
lastReturnedIndex= 0
unseen= 4278190080
unseenIndex= 0
lastReturned= 8388608
lastReturnedIndex= 0
unseen= 4261412864
unseenIndex= 0
lastReturned= 16777216
lastReturnedIndex= 0
unseen= 4227858432
unseenIndex= 0
lastReturned= 33554432
lastReturnedIndex= 0
unseen= 4160749568
unseenIndex= 0
lastReturned= 67108864
lastReturnedIndex= 0
unseen= 4026531840
unseenIndex= 0
lastReturned= 134217728
lastReturnedIndex= 0
unseen= 3758096384
unseenIndex= 0
lastReturned= 268435456
lastReturnedIndex= 0
unseen= 3221225472
unseenIndex= 0
lastReturned= 536870912
lastReturnedIndex= 0
unseen= 2147483648
unseenIndex= 0
lastReturned= 1073741824
lastReturnedIndex= 0
unseen= 0
unseenIndex= 0
lastReturned= 2147483648
lastReturnedIndex= 0
unseen= 4296015870
unseenIndex= 1
lastReturned= 1
lastReturnedIndex= 1
unseen= 4296015868
unseenIndex= 1
lastReturned= 2
lastReturnedIndex= 1
unseen= 4296015864
unseenIndex= 1
lastReturned= 4
lastReturnedIndex= 1
unseen= 4296015856
unseenIndex= 1
lastReturned= 8
lastReturnedIndex= 1
unseen= 4296015840
unseenIndex= 1
lastReturned= 16
lastReturnedIndex= 1
unseen= 4296015808
unseenIndex= 1
lastReturned= 32
lastReturnedIndex= 1
unseen= 4296015744
unseenIndex= 1
lastReturned= 64
lastReturnedIndex= 1
unseen= 4296015616
unseenIndex= 1
lastReturned= 128
lastReturnedIndex= 1
unseen= 4296015360
unseenIndex= 1
lastReturned= 256
lastReturnedIndex= 1
unseen= 4296014848
unseenIndex= 1
lastReturned= 512
lastReturnedIndex= 1
unseen= 4296013824
unseenIndex= 1
lastReturned= 1024
lastReturnedIndex= 1
unseen= 4296011776
unseenIndex= 1
lastReturned= 2048
lastReturnedIndex= 1
unseen= 4296007680
unseenIndex= 1
lastReturned= 4096
lastReturnedIndex= 1
unseen= 4295999488
unseenIndex= 1
lastReturned= 8192
lastReturnedIndex= 1
unseen= 4295983104
unseenIndex= 1
lastReturned= 16384
lastReturnedIndex= 1
unseen= 4295950336
unseenIndex= 1
lastReturned= 32768
lastReturnedIndex= 1
unseen= 4295884800
unseenIndex= 1
lastReturned= 65536
lastReturnedIndex= 1
unseen= 4295753728
unseenIndex= 1
lastReturned= 131072
lastReturnedIndex= 1
unseen= 4295491584
unseenIndex= 1
lastReturned= 262144
lastReturnedIndex= 1
unseen= 4294967296
unseenIndex= 1
lastReturned= 524288
lastReturnedIndex= 1
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 83 out of bounds for length 83
        at java.base/java.util.JumboEnumSet$EnumSetIterator.next(JumboEnumSet.java:144)
        at java.base/java.util.JumboEnumSet$EnumSetIterator.next(JumboEnumSet.java:97)
        at jdk.compiler/com.sun.tools.javac.main.Option.lookup(Option.java:917)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:374)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:193)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:229)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```

**Comment by zifeihan** [comment]
已提交PR：https://github.com/openjdk-riscv/jdk11u/pull/309
