### ISSUE TITLE
templateTable_riscv32.cpp:index_check 函数修复

### ISSUE THREAD

**Issue by zifeihan** [openjdk-riscv/jdk11u#314]
在 OpenJDK for RV32G 中，Long类型数据需要占用两个寄存器（x10, x11），发现在`void TemplateTable::index_check(Register array, Register index)`中存在着一个特殊判断，在进入这个判断中错误的将 x11 寄存器覆盖了。
```
void TemplateTable::index_check(Register array, Register index)
{
  // destroys x11, t0
  // check array
  __ null_check(array, arrayOopDesc::length_offset_in_bytes());
  // sign extend index for use by indexed load
  // check index
  const Register length = t0;
  __ lw(length, Address(array, arrayOopDesc::length_offset_in_bytes()));
  if (index != x11) {
    assert(x11 != array, "different registers");
    __ mv(x11, index);
  }
  Label ok;
  __ add(index, index, zr);
  __ bltu(index, length, ok);
  __ mv(x13, array);
  __ mv(t0, Interpreter::_throw_ArrayIndexOutOfBoundsException_entry);
  __ jr(t0);
  __ bind(ok);
}
```
测试用例：
```
public class TestLastore {
    public static void main(String[] args) {
        long elements[] = new long[2];
        for (int i = 0; i < elements.length; i++) {
            System.out.println(elements[i]);
            elements[i] = -1;
            System.out.println(elements[i]);
        }
    }
}
```
在修复之前结果，可以看到 elements[i] 的数据是错误的：
![image](https://user-images.githubusercontent.com/16839929/148744073-f46bfa9a-2e99-494c-9e0b-bc4a045f0f2c.png)
在PR：https://github.com/openjdk-riscv/jdk11u/pull/316 ，修复后的结果，修复后结果是正确的：
![image](https://user-images.githubusercontent.com/16839929/148746306-75d61f0a-43fd-4281-a708-1399376df5b5.png)

**Comment by shining1984** [comment]
目前#315 修改是直接删除了对于index往x11里移动的动作，这是不对的。
往下的操作中，TemplateInterpreterGenerator::generate_ArrayIndexOutOfBounds_handler()里会直接用到x11里的index，并且默认index已经放在了x11里。
但是，lastore\aastore传递的index本来就不在x11里：
![image](https://user-images.githubusercontent.com/3916635/148751502-2aa58e18-a6d3-4a9f-9591-8c1d8bb71138.png)
![image](https://user-images.githubusercontent.com/3916635/148751524-ea780017-7db6-4ca3-8212-6c306efe420f.png)
#315之中的判断代码直接删除了之后，会导致lastore\aastore的处理过程中，index越界之后，调用generate_ArrayIndexOutOfBounds_handler()时候，从x11取出来非index数据进行操作。
所以，#315保证了数据的正确，但是导致了index的错误。

**Comment by shining1984** [comment]
建议：可以取一个之前没用过的寄存器，比如x14，将index都强制放到x14中。后续在TemplateInterpreterGenerator::generate_ArrayIndexOutOfBounds_handler()里默认从x14来取index。

**Comment by zifeihan** [comment]
感谢史老师提的意见，已提交新的修复：https://github.com/openjdk-riscv/jdk11u/pull/316 ，另外新增对Long 类型数组溢出的测试用例，测试用例符合结果（左边是 OpenJDK for RV32G 结果，右边是 BishengJDK 结果）：

![image](https://user-images.githubusercontent.com/16839929/148762884-64104033-cc82-427c-abac-bc176a546576.png)

**Comment by zifeihan** [comment]
![image](https://user-images.githubusercontent.com/16839929/148763054-f92d590f-538d-499b-871f-4b6efd8e0fb4.png)
这里需要关注一下，今后可以将该方法的入参 index 都优化为使用 x14 ，这样就不用多一条指令了。

**Comment by shining1984** [comment]
> ![image](https://user-images.githubusercontent.com/16839929/148763054-f92d590f-538d-499b-871f-4b6efd8e0fb4.png) 这里需要关注一下，今后可以将该方法的入参 index 都优化为使用 x14 ，这样就不用多一条指令了。

这种修改方式改动较大，成本远比目前这种方式要大的多。这个需要再考虑。

**Comment by zifeihan** [comment]
在调试 javac 时发生如下报错，java 迭代器使用 `public boolean hasNext()` 方法判断。我们在 `public boolean hasNext()` 方法中打印`unseen` 变量，也可以看到修复前后的数据变化，但是在后面数据还有差异，目前还在排查中。
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 83 out of bounds for length 83
	at java.base/java.util.JumboEnumSet$EnumSetIterator.next(JumboEnumSet.java:141)
	at java.base/java.util.JumboEnumSet$EnumSetIterator.next(JumboEnumSet.java:97)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at jdk.compiler/com.sun.tools.javac.main.Option.showHelp(Option.java:944)
	at jdk.compiler/com.sun.tools.javac.main.Option$18.process(Option.java:374)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:207)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```
![40051641817226_ pic_hd](https://user-images.githubusercontent.com/16839929/148765192-803cb213-9094-428e-aff3-291618a06c7b.jpg)
![40041641817212_ pic_hd](https://user-images.githubusercontent.com/16839929/148765207-ac004f59-9b3c-4c91-97fb-c8b30ee56568.jpg)

**Comment by zifeihan** [comment]
对Long 类型数据操作的结果如下（数据也是正常的）：
![image](https://user-images.githubusercontent.com/16839929/148765917-fc556835-aa2c-446a-9e77-5d5312347a40.png)
